// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "809a2a4f-ebf3-4ecb-9408-ff35cff4f5ec";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTankPercentageChange();
void onActivateDispensingChange();
void onDispenseButtonChange();
void onDispensingActiveChange();
void onIsAquaWiseEnableChange();
void onIsWaterDispensingChange();

int tankPercentage;
bool activateDispensing;
bool dispenseButton;
bool dispensingActive;
bool isAquaWiseEnable;
bool isWaterDispensing;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(tankPercentage, READWRITE, ON_CHANGE, onTankPercentageChange);
  ArduinoCloud.addProperty(activateDispensing, READWRITE, ON_CHANGE, onActivateDispensingChange);
  ArduinoCloud.addProperty(dispenseButton, READWRITE, ON_CHANGE, onDispenseButtonChange);
  ArduinoCloud.addProperty(dispensingActive, READWRITE, ON_CHANGE, onDispensingActiveChange);
  ArduinoCloud.addProperty(isAquaWiseEnable, READWRITE, ON_CHANGE, onIsAquaWiseEnableChange);
  ArduinoCloud.addProperty(isWaterDispensing, READWRITE, ON_CHANGE, onIsWaterDispensingChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
